[TrivialFix] Fix documentation job failing on underline.
This PS fixes a trivial underline issue when running tox -e docs

Traceback:

Warning, treated as error:
/opt/stack/armada/docs/source/operations/guide-api.rst:117:Title underline too short.

POST ``/validatedesign``
-----------------
ERROR: InvocationError: '/opt/stack/armada/.tox/docs/bin/python setup.py build_sphinx'

This also fixes a recent change to validate endpoint being renamed to
validatedesign not also getting reflected in a unit test. This patch
unblocks the Armada gate by correcting the test.

Change-Id: I48852507b6868527fc08d661ef2c276e95db6469